config/routes.rb
RiMa::Application.routes.draw do
  resources :periods

  resources :risks

  resources :locations

  resources :types
  
  root to: 'risks#index'

end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :from_date, :from_time, :risk_id, :to_date, :to_time, :probability, :impact
  belongs_to :risk
  
  
  validates :probability, :impact, :inclusion => 0..4
  
  @impact_strings = [
                     "Negligible",
                     "Minor",
                     "Major",
                     "Severe",
                     "Catastrophic"
                    ]

  @probability_strings = [
                          "Very Low",
                          "Low",
                          "Equally likely",
                          "High",
                          "Very High"
                         ]
                        
  
  def self.impact_strings
    @impact_strings
  end

  def self.probability_strings
    @probability_strings
  end
  
  def self.impact_to_text(number)
    impact_strings[number]
  end

  def self.probability_to_text(number)
    probability_strings[number]
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @periods }
    end
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
    @period = Period.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @period }
    end
  end

  # GET /periods/new
  # GET /periods/new.json
  def new
    @period = Period.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @period }
    end
  end

  # GET /periods/1/edit
  def edit
    @period = Period.find(params[:id])
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(params[:period])

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render json: @period, status: :created, location: @period }
      else
        format.html { render action: "new" }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /periods/1
  # PUT /periods/1.json
  def update
    @period = Period.find(params[:id])

    respond_to do |format|
      if @period.update_attributes(params[:period])
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period = Period.find(params[:id])
    @period.destroy

    respond_to do |format|
      format.html { redirect_to periods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<%= form_for(@period) do |f| %>
  <% if @period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% @period.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :risk_id %><br />
    <%= f.number_field :risk_id %>
  </div>
  <div class="field">
    <%= f.label :from_date %><br />
    <%= f.date_select :from_date %>
  </div>
  <div class="field">
    <%= f.label :from_time %><br />
    <%= f.time_select :from_time %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br />
    <%= f.date_select :to_date %>
  </div>
  <div class="field">
    <%= f.label :to_time %><br />
    <%= f.time_select :to_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/periods/edit.html.erb
<h1>Editing period</h1>

<%= render 'form' %>

<%= link_to 'Show', @period %> |
<%= link_to 'Back', periods_path %>

app/views/periods/index.html.erb
<h1>Listing periods</h1>

<table class="table table-striped">
  <tr>
    <th>Risk</th>
    <th>From date</th>
    <th>From time</th>
    <th>To date</th>
    <th>To time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @periods.each do |period| %>
  <tr>
    <td><%= period.risk_id %></td>
    <td><%= period.from_date %></td>
    <td><%= period.from_time %></td>
    <td><%= period.to_date %></td>
    <td><%= period.to_time %></td>
    <td><%= link_to 'Show', period %></td>
    <td><%= link_to 'Edit', edit_period_path(period) %></td>
    <td><%= link_to 'Destroy', period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Period', new_period_path %>

app/views/periods/new.html.erb
<h1>New period</h1>

<%= render 'form' %>

<%= link_to 'Back', periods_path %>

app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Risk:</b>
  <%= @period.risk_id %>
</p>

<p>
  <b>From date:</b>
  <%= @period.from_date %>
</p>

<p>
  <b>From time:</b>
  <%= @period.from_time %>
</p>

<p>
  <b>To date:</b>
  <%= @period.to_date %>
</p>

<p>
  <b>To time:</b>
  <%= @period.to_time %>
</p>


<%= link_to 'Edit', edit_period_path(@period) %> |
<%= link_to 'Back', periods_path %>