config/routes.rb
RiMa::Application.routes.draw do
  resources :periods

  resources :risks

  resources :locations

  resources :types
  
  root to: 'risks#index'

end

app/models/risk.rb
class Risk < ActiveRecord::Base
  attr_accessible :description, :from_date, :from_time, :location_id, :to_date, :to_time, :type_id, :periods_attributes
  belongs_to :type
  belongs_to :location
  has_many :periods
  
  accepts_nested_attributes_for :periods
  
  def self.search(search)
    if search
      search_condition = "%" + search + "%"
      find(:all, :condition => ['description LIKE ?', search_condition])
    else
      find(:all)
    end
  end
  
end

app/controllers/risks_controller.rb
class RisksController < ApplicationController
  # GET /risks
  # GET /risks.json
  def index
    @risks = Risk.all
    @risks = Risk.order("description").paginate :page => params['page'], :per_page => 5

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @risks }
    end
  end

  # GET /risks/1
  # GET /risks/1.json
  def show
    @risk = Risk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @risk }
    end
  end

  # GET /risks/new
  # GET /risks/new.json
  def new
    @risk = Risk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @risk }
    end
  end

  # GET /risks/1/edit
  def edit
    @risk = Risk.find(params[:id])
  end

  # POST /risks
  # POST /risks.json
  def create
    @risk = Risk.new(params[:risk])

    respond_to do |format|
      if @risk.save
        format.html { redirect_to @risk, notice: 'Risk was successfully created.' }
        format.json { render json: @risk, status: :created, location: @risk }
      else
        format.html { render action: "new" }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /risks/1
  # PUT /risks/1.json
  def update
    @risk = Risk.find(params[:id])

    respond_to do |format|
      if @risk.update_attributes(params[:risk])
        format.html { redirect_to @risk, notice: 'Risk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /risks/1
  # DELETE /risks/1.json
  def destroy
    @risk = Risk.find(params[:id])
    @risk.destroy

    respond_to do |format|
      format.html { redirect_to risks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/risks_helper.rb
module RisksHelper
end

app/views/risks/_form.html.erb
<%= nested_form_for(@risk) do |f| %>
  <% if @risk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@risk.errors.count, "error") %> prohibited this risk from being saved:</h2>

      <ul>
      <% @risk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.select :location_id, Location.all.map {|x| [x.name, x.id]} %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.select :type_id, Type.all.map {|x| [x.name, x.id]} %>
  </div>
  <div class="field">
    <%= f.label :from_date %><br />
    <%= f.date_select :from_date %>
  </div>
  <div class="field">
    <%= f.label :from_time %><br />
    <%= f.time_select :from_time %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br />
    <%= f.date_select :to_date %>
  </div>
  <div class="field">
    <%= f.label :to_time %><br />
    <%= f.time_select :to_time %>
  </div>
  
  <br />
  
  <div>
  <%= f.fields_for :periods do |period_form| %>
    <br />
    <% hash = Hash[Period.probability_strings.map.with_index.to_a] %>
    <%= period_form.label "From:"%><br />
    <%= period_form.date_select :from_date %><br />
    <%= period_form.time_select :from_time %><br />
    <%= period_form.label "To:"%><br />
    <%= period_form.date_select :to_date %><br />
    <%= period_form.time_select :to_time %><br />
    <%= period_form.label "Probability"%><br />
    <%= period_form.select :probability, Period.probability_strings.map {|x| [x.to_s, hash[x.to_s]]} %><br />
    <%= period_form.label "Impact"%><br />
    <%= period_form.number_field :impact %><br />
    <%= period_form.link_to_remove "Remove this period" %>
  <% end %>
  <p><%= f.link_to_add "Add a period", :periods %></p>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/risks/_table.html.erb
<table class="table table-striped">
  <tr>
    <th>Location</th>
    <th>Description</th>
    <th>Type</th>
    <th>From date</th>
    <th>From time</th>
    <th>To date</th>
    <th>To time</th>
    <th>Periods</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% risks.each do |risk| %>
  <tr>
    <td><%= risk.location.name %></td>
    <td><%= risk.description %></td>
    <td><%= risk.type.name %></td>
    <td><%= risk.from_date %></td>
    <td><%= risk.from_time %></td>
    <td><%= risk.to_date %></td>
    <td><%= risk.to_time %></td>
    <td><%= risk.periods.count %></td>
    <td><%= link_to 'Show', risk %></td>
    <td><%= link_to 'Edit', edit_risk_path(risk) %></td>
    <td><%= link_to 'Destroy', risk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @risks %>

app/views/risks/edit.html.erb
<h1>Editing risk</h1>

<%= render 'form' %>

<%= link_to 'Show', @risk %> |
<%= link_to 'Back', risks_path %>

app/views/risks/index.html.erb
<h1>Listing risks</h1>

<%= form_tag(risks_path, :method => "get", class: "navbar-form", id: "search-form") do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :class => "btn", :name => nil %>
</p>
<% end %>

<%= render :partial => "table", :locals => { :risks => @risks } %>

<br />

<a class="btn btn-large btn-info" href=<%= new_risk_path %>>New Risk</a>

app/views/risks/new.html.erb
<h1>New risk</h1>

<%= render 'form' %>

<%= link_to 'Back', risks_path %>

app/views/risks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @risk.location.name %>
</p>

<p>
  <b>Description:</b>
  <%= @risk.description %>
</p>

<p>
  <b>Type:</b>
  <%= @risk.type.name %>
</p>
<!--
<p>
  <b>From date:</b>
  <%= @risk.from_date %>
</p>

<p>
  <b>From time:</b>
  <%= @risk.from_time %>
</p>

<p>
  <b>To date:</b>
  <%= @risk.to_date %>
</p>

<p>
  <b>To time:</b>
  <%= @risk.to_time %>
</p> -->
<br />


<p>
  
  <% @risk.periods.each do |periodo| %>
  <br />
  <b>Period:</b> 
    <%= periodo.from_date %> - 
    <%= periodo.to_date %>
  <br />
  <b>Probability:</b>
    <%= Period.probability_to_text(periodo.probability) %>
  <br />
  <b>Impact:</b>
    <%= Period.impact_to_text(periodo.impact) %>
  <br />
  <% end %>
</p>


<%= link_to 'Edit', edit_risk_path(@risk) %> |
<%= link_to 'Back', risks_path %>